# Generated by Django 2.1.14 on 2020-01-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_dect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='MoodImage',
        ),
    ]
